- Sources/YumemiWeather/YumemiWeather.swift
- jsonStringのバリデーション用で、jsonStringはすべてのAPIに使われていなくて、レスポンスのデコードエラーと勘違いされやすい
- ネーミング変更で意味合いをはっきりする対応を考えたけど、結局バリデーション用で使う側にとっては`invalidParameterError`の方が適切
- `jsonDecodeError`を削除
- デコード失敗も`invalidParameterError`にする
> 勘違いされやすいjsonDecodeErrorを削除

- Documentation/BugFix.md
リポ自体がまだ対応されていないですが、まあ一応世の流れ的に `master` ブランチを `main` に直した方がいいかと思って()
> メインブランチを `main` にリネーム

- Documentation/YumemiWeather.md
- jsonDecodeError は過去の対応で削除済み
- https://github.com/yumemi-inc/ios-training/pull/2
- YumemiWeather のドキュメントに削除漏れと思われるものを発見
- Error type から jsonDecodeError を削除
問題なさそうだったので PR を作らせていただきました。問題ありそうでしたらクローズしちゃってください 🙏
> Error type の jsonDecodeError 削除漏れを削除

- Example/Example.xcodeproj/project.pbxproj
- [Session 12](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/BugFix.md)で利用するExampleの[xcodeproj](https://github.com/yumemi-inc/ios-training/tree/main/Example/Example.xcodeproj)がBuildできない問題を修正します
- https://github.com/yumemi-inc/ios-training/pull/5 の関連だと思います 
- ref: https://github.com/yonaskolb/Mint/issues/179 
課題自体で提示されている不具合とは別件と解釈してPRを出しました。
もし意図が誤っていたらCloseしてください 🙏
> [Session 12] ExampleのxcodeprojがBuildできない問題を修正

- Documentation/VC_Lifecycle.md
fixes #20
[Session6](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/VC_Lifecycle.md)のWork with ViewControllersがSwiftUIのドキュメントにリダイレクトされてしまうので、UIViewControllerのレファレンスページへのリンクに変更しました。
非公式ですが、[翻訳されたアーカイブの記事](https://rusutikaa.github.io/docs/developer.apple.com/library/archive/referencelibrary/GettingStarted/DevelopiOSAppsSwift/WorkWithViewControllers.html)からおそらくこの図のライフサイクルについてリファレンスしたかったと推測しました。
[UIViewControllerのAPIリファレンスページ](https://developer.apple.com/documentation/uikit/uiviewcontroller)に同様の図があったのでこちらをリンク先として設定しました。
| 翻訳されたアーカイブの記事 | UIViewControllerのAPIリファレンスページ |
| -- | -- |
| <img width="699" alt="Screen Shot 2022-04-04 at 23 53 23" src="https://user-images.githubusercontent.com/5770480/161571145-8655021e-291c-4179-822b-61aacfdb77ab.png"> | <img width="838" …
> Session6のWork with View Controllersリンクを更新

- Documentation/API.md
- Documentation/Error.md
- Sources/YumemiWeather/YumemiDisaster.swift
- Sources/YumemiWeather/YumemiWeather.swift
- Sources/YumemiWeather/YumemiWeatherList.swift
- Tests/YumemiWeatherTests/YumemiWeatherListTests.swift
- Tests/YumemiWeatherTests/YumemiWeatherTests.swift
iOS 研修をする時、最初に読むコードは YumemiWeather のソースコードだから、もっときれいにしたいと思います。
なお、これらの修正は研修最終課題の Example にはあえて施さない。
[API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines) により、
> **Avoid abbreviations.** Abbreviations, especially non-standard ones…
Temp は標準的な略語ではないため、省略すべきではない。
自分が研修をやる時にももやもやしてたけど、`sunny` `cloudy` を表示する `Weather`と、温度などの情報を含む `Response` を返す方法 `fetchWeather(_ jsonString:)` が名前が混同している。
Weather の曖昧さを回避するために改名する。
ちょうど WWDC22 でリリースされた WeatherKit にも[同じもの WeatherCondition](https://developer.apple.com/documentation/weatherkit/weathercondition) があるので。
合わせて、天気状況、温度などを含む天気情報の `Response` を `Weather` に変えるべきだと思いますが、パッケージ内部しか使われなくて、Response の意味も含んでいるので、一旦放置します。何か意見があればありがたいです。
- Json -> JSON
- JSON 文字列の例を全部コードブロック化
こうなります。
> コード文言とコメントの更新

- Documentation/Delegate.md
- README.md
> Delegateセクションを先に取り組む

- Documentation/Error.md
#27 エラーハンドリングより前に Delegate を実装することになったので。
> エラーハンドリングに Delegate を絡める

- Documentation/UnitTest.md
レビューをしていて、スタブに対して、モックと命名してしまいがちな点が気になりました（自分もやってました）
図解のわかりやすい記事のリンクを追加し、自学できるようにしたいと考えました。
特に記事中の以下の図が理解の助けになると思いました。
https://goyoki.hatenablog.com/entry/20120301/1330608789
> テストダブルについての参考記事のリンクを追加

- Documentation/UITableView.md
Apple HIG のサイトが更新されたため
- fixes #47
> pull to refresh のリンク修正

- .github/workflows/test.yml
XCTest を動かす GitHub Actions を追加しました。
以下の PR レビュー時にテストコードを書いてもらってパスすることを確認したいと思ったのが動機です。
- #49 
結果の整形に [xcresulttool](https://github.com/kishikawakatsumi/xcresulttool) を利用しています。
以下のようにテスト結果が表示されます。
https://github.com/yumemi-inc/ios-training/actions/runs/6667656847/job/18121662855
> Add GitHub Actions Test

- .github/workflows/test.yml
With pull_request trigger, we can't attach write permissions to GitHub Actions for the pull requests from a forked repository. This pull request proposes to use pull_request_target trigger instead, so it'll always refer the workflow in the default branch (instead of HEAD), with ability to give write permissions.
> ci: Use pull_request_target trigger instead

- Sources/YumemiWeather/YumemiWeatherList.swift
https://github.com/yumemi-inc/ios-training/issues/49#issuecomment-1808139227 (fetchWeatherList()の引数areaは第一字が大文字でないと正常に値を返さない問題)
で、古宮さんに
> API ReferenceのtypoなのでA案のドキュメント修正が妥当
と教えていただいたので、API Referenceのtypo修正のPRです。
[API reference](https://yumemi-inc.github.io/ios-training/documentation/yumemiweather/yumemiweather/asyncfetchweatherlist(_:))はGitHub Actionで自動生成される？という認識なので、ソースファイル上のコメントのみを修正しました。
> fixed Typos on comments on fetch...List() APIs

- Documentation/ThreadBlock.md
本人に気づいてもらうのが一番ですが、
気づきにくいようなのと、公式のドキュメントを読んでもらうのはおすすめしたいので、最初から明記できればと思いました。
合わせて Reload に時間がかかるようになったので、連続タップの対応も必要になることを追記したい気もします。
何か良い書き方があれば
> スレッドブロックのセッションに非同期テスト対応を明記

- Documentation/UnitTest.md
`Impl` という命名が Swift API Guideline にはそぐわないので、課題の表記に引きずられないように変えてみます。
ただ、あまり具体的な命名をここでしてしまうと今度はそれに引きずられそうなので、それも避けたい気持ちもあります。
他に良い表現があればコメントいただきたいです。
> 実装クラスの Impl という表記を避ける

- .github/workflows/test.yml
サポートの終了した Node 16 から 20 への切り替え対応です。
[actions 実行時](https://github.com/yumemi-inc/ios-training/actions/runs/7956513879)に以下の警告が出力されています。
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, kishikawakatsumi/xcresulttool@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
kishikawakatsumi/xcresulttool の方は未対応です。 PR は作成されていました。
- https://github.com/kishikawakatsumi/xcresulttool/pull/760
> Upgrade actions/checkout v4

- Sources/YumemiWeather/YumemiWeather.APIQuality.swift
- Sources/YumemiWeather/YumemiWeather.swift
- Sources/YumemiWeather/YumemiWeatherList.swift
- Tests/YumemiWeatherTests/TestMethods.swift
- Tests/YumemiWeatherTests/YumemiWeatherListTests.swift
- Tests/YumemiWeatherTests/YumemiWeatherTests.swift
YumemiWeather API が無作為にエラーを発生させるタイミングを制御できないとテストコードの記載に支障をきたすため、Internal プロテクションレベルからであれば発生タイミングをカスタマイズ可能にしました。
> YumemiWeather API が無作為にエラーを返す頻度をコントロール可能にしました。

- Tests/YumemiWeatherTests/YumemiWeatherListTests.swift
- Tests/YumemiWeatherTests/YumemiWeatherTests.swift
複数行文字列の内容上のインデントは閉じ記号の位置で揃えられるため、行頭に揃えなくても大丈夫です。
行頭に揃えると全体的なインデントが複雑になる印象を持つため、そのリテラルが使われるコード行のインデントに揃えて記載するようにしてみました。
> 複数行の文字列リテラルのインデントが周囲と乖離しないようにしました。

- Example/Example/Data/Weather.swift
- Example/Example/Data/WeatherError.swift
- Example/Example/Model/DisasterModel.swift
- Sources/YumemiWeather/YumemiDisaster.swift
必要性のない `import Foundation` を削除してみました。
削除しなくても支障のないところなのと、一般に Foundation は必要性に関係なく取り込むこともある様子なので、方針によってはこの PR は適用しない選択もあるかもしれません。
> 不必要な import を削除しました。

- .github/workflows/test.yml
- Exampleもテストに追加
- #85 の発見漏れ防止
```json
[
{
"scheme": "YumemiWeather",
"dir": "."
},
{
"scheme": "Example",
"dir": "Example"
}
]
```
- Exampleが失敗なのは #85 で解消
https://github.com/yumemi-inc/ios-training/actions/runs/9949804008
> feat: test matrix [skip ci]
